{% set version = "0.12.0" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: jupyter_events
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-events/jupyter_events-{{ version }}.tar.gz
  sha256: fc3fce98865f6784c9cd0a56a20644fc6098f21c8c33834a8d9fe383c17e554b

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.0
  run:
    - jsonschema-with-format-nongpl >=4.18.0
    - packaging
    - python >={{ python_min }}
    - python-json-logger >=2.0.4
    - pyyaml >=5.3
    - referencing
    - rfc3339-validator
    - rfc3986-validator >=0.1.1
    - traitlets >=5.3

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

outputs:
  - name: jupyter_events

  - name: jupyter_events_with_cli
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyter_events") }}
        - click
        - rich
    test:
      imports:
        - jupyter_events
        - jupyter_events.cli
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check

  - name: _jupyter_events_tests
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyter_events") }}
        - {{ pin_subpackage("jupyter_events_with_cli") }}
    test:
      source_files:
        - tests
        - pyproject.toml
      requires:
        - coverage
        - pytest-asyncio >=0.19.0
        - pytest-console-scripts
        - python {{ python_min }}
      imports:
        - jupyter_events
        - jupyter_events.cli
      commands:
        - coverage run --source=jupyter_events --branch -m pytest -vv --tb=long --color=yes
        - coverage report --show-missing --skip-covered --fail-under=81

about:
  home: https://pypi.org/project/jupyter-events
  dev_url: https://github.com/jupyter/jupyter_events
  summary: Jupyter Event System library
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://jupyter-events.readthedocs.io

extra:
  feedstock-name: jupyter_events
  recipe-maintainers:
    - Zsailer
    - blink1073
    - afshin
    - bollwyvl
